site_name: CREDENCE Documentation

theme:
  name: material

nav:
  - Home: index.md
  - Analyse Module: analyse.md
  - Admin Module: admin.md
  - History Module: history.md
  - Database Relationships: database.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
